[package]
name = "dnd-rs"
version = "0.1.0"
edition = "2024"

[dependencies]
fastrand = "2.4.1"
tyche = "0.3.1"  # for dice
ratatui = "0.30"
crossterm = "0.29"
regex = "1.12.3"

[profile.dev]
opt-level = 0
debug = true
debug-assertions = true
overflow-checks = true

[profile.dev.package."*"]
opt-level = 3

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
strip = true
